FROM python:3-slim

COPY [".", "/app"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev nodejs npm \
    && cd /app && pip install -r requirements.txt \
    && cd /app/react-app && npm install && npm run build \
    && apt-get remove -y build-essential \
    && apt-get autoremove -y && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0", "django_app.wsgi"]
