FROM node:18-bullseye-slim AS js-builder

COPY ["react-app/", "/app"]

RUN cd /app && npm install && npm run build

FROM python:3-slim

COPY --from=js-builder ["/app/build/", "/app/"]

COPY [".", "/app"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && cd /app && pip install -r requirements.txt \
    && apt-get remove -y build-essential \
    && apt-get autoremove -y && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0", "django_app.wsgi"]
